services:
  postgres:
    image: docker.io/library/postgres:17.11-alpine3.24
    container_name: bulk-url-checker-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_checker

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d url_checker"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: docker.io/library/redis:8.8.2-alpine3.23
    container_name: bulk-url-checker-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: