POST http://localhost:3001/batches
Content-Type: application/json

{
  "urls": [
    "https://example.com",
    "https://google.com",
    "https://github.com"
  ]
}

###
# failled
POST http://localhost:3001/batches
Content-Type: application/json

{
  "urls": [
    "https://example.com",
    "https://httpbin.org/status/404",
    "https://httpbin.org/status/500"
  ]
}

###

GET http://localhost:3001/batches
Content-Type: application/json

###

GET http://localhost:3001/batches/23a6d24f-f30e-4b77-aaf8-9fdf70992741
Content-Type: application/json

###